### ISSUE TITLE
Any performance testing data?

### ISSUE THREAD

**Issue by Bisstocuz** [huantt/plaintext-extractor#1]
Good module! Is there any performance testing data I can see?

I wanna know this module's performance.

**Comment by huantt** [comment]
Which metric do you want to benchmark?

Could you provide the benchmark scenario?

**Comment by Bisstocuz** [comment]
> Which metric do you want to benchmark?
> 
> Could you provide the benchmark scenario?

About memory allocation and execution time for big markdown docs

Maybe [validator](https://github.com/go-playground/validator/blob/master/README.md) will be a good testdata.

**Comment by huantt** [comment]
Would you be willing to contribute to this repository by writing some benchmarks? I would really appreciate it.
