### ISSUE TITLE
feature request: extract all links

### ISSUE THREAD

**Issue by Bisstocuz** [huantt/plaintext-extractor#2]
As title, it will be great to provide a new extractor for markdown links.

**Comment by huantt** [comment]
Thanks for your feedback. I understand that you would like me to add a Markdown link extractor to my repository. However, I want to keep my repository as simple as possible, and I think that adding this logic would make it more complex.

I would prefer you to create your own repository that uses an HTTP request to get the link response, and then use my repository to extract the output. This would allow you to have more control over the process, and it would also be more scalable.
